[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=triton_inference_clients"
pythonpath = [
    ".",
    "src",
]
testpaths = [
    "tests",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]